config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
    get '/login' => 'devise/sessions#new'
    get '/register' => 'devise/registrations#new'
    get '/account_update' => 'devise/registrations#edit'
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do

      get 'movies' => 'pages#movies'

      get 'tv-series' => 'pages#series'

      get 'movies/:id' => 'pages#show'

      get 'tv-series/:id' => 'pages#view'

    end
  end

  resources :activities
  resources :posts
  resources :genres, except: [:show, :edit, :post]
  resources :siri_genres, except: [:show, :edit, :post]
  resources :anime_genres, except: [:show, :edit, :post]
  resources :asian_genres, except: [:show, :edit, :post]
  resources :users, except: [:show, :edit, :post, :destroy, :new, :create] do
    member do
      patch :revoke
      patch :grant
    end
  end
  resources :siris do
    resources :seasons, except: [:show] do
      resources :episodes
    end
  end
  resources :animes do
    resources :anime_seasons, except: [:show] do
      resources :anime_episodes
    end
  end
  resources :asians do
    resources :asian_seasons, except: [:show] do
      resources :asian_episodes
    end
  end
  resources :requests, only: [:new, :create, :show] do
    member do
      patch :set_pending
      patch :set_approved
      patch :set_rejected
      patch :set_closed
    end
  end
  resources :reports, only: [:new, :create, :show] do
    member do
      patch :mark_pending
      patch :mark_solved
    end
  end
  resources :bookmarks, only: [:create, :destroy]

  get '/dashboard' => 'dashboards#index'

  get 'movies/:sort/:id' => 'pages#show', as: 'genre_show'
  get 'tv-series/:view/:id' => 'pages#view', as: 'siri_genre_show'
  get '/tv-series/:view/:siri_id/:season_id-:id' => 'pages#ep', as: 'watch_ep'
  get 'anime-series/:anime_view/:id' => 'pages#anime_view', as: 'anime_genre_show'
  get '/anime-series/:anime_view/:anime_id/:anime_season_id-:id' => 'pages#anime_ep', as: 'watch_anime_ep'
  get 'asian-drama/:asian_view/:id' => 'pages#asian_view', as: 'asian_genre_show'
  get '/asian-drama/:asian_view/:asian_id/:asian_season_id-:id' => 'pages#asian_ep', as: 'watch_asian_ep'

  get '/developer' => 'pages#developer'
  get '/dmca' => 'pages#dmca'

  scope :q do
    get 'search' => 'pages#search', as: :search
  end

  get 'movies' => 'pages#movies'
  get 'movies/:sort/' => 'pages#movies', as: 'genre_index'
  get 'tv-series' => 'pages#series'
  get 'tv-series/:view/' => 'pages#series', as: 'siri_genre_index'
  get 'anime-series' => 'pages#anime_series'
  get 'anime-series/:anime_view/' => 'pages#anime_series', as: 'anime_genre_index'
  get 'asian-drama' => 'pages#asian_series'
  get 'asian-drama/:asian_view/' => 'pages#asian_series', as: 'asian_genre_index'

  get 'movies/all/page/:page' => 'pages#movies'
  get 'movies/:sort/page/:page' => 'pages#movies'
  get 'tv-series/all/page/:page' => 'pages#series'
  get 'tv-series/:view/page/:page' => 'pages#series'
  get 'anime-series/all/page/:page' => 'pages#anime_series'
  get 'anime-series/:anime_view/page/:page' => 'pages#anime_series'
  get 'asian-drama/all/page/:page' => 'pages#asian_series'
  get 'asian-drama/:asian_view/page/:page' => 'pages#asian_series'

  root 'pages#index'

  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/anime_genre.rb
# == Schema Information
#
# Table name: anime_genres
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  slug       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class AnimeGenre < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders, :history]

	has_many :animes
end

app/controllers/anime_genres_controller.rb
class AnimeGenresController < ApplicationController
  before_action :authenticate_user!
  before_filter :admin_only

  def index
  	@anime_genres = AnimeGenre.all
  end

  def new
  	@anime_genre ||= AnimeGenre.new
  	render
  end

  def create
  	@anime_genre = AnimeGenre.create!(anime_genre_params)
  	respond_to do |format|
			format.html { redirect_to anime_genres_path, notice: "Good! Anime Genre has been added" }
			format.js
		end
  end

  def destroy
  	@anime_genre = AnimeGenre.destroy(params[:id])
		redirect_to anime_genres_path, notice: "Good! Anime Genre has been remove"
  end

  private

  def anime_genre_params
  	params.require(:anime_genre).permit(:name)
  end
end

app/helpers/anime_genres_helper.rb
module AnimeGenresHelper
end

app/views/anime_genres/_anime_genre.html.haml
%td= anime_genre.name
%td= anime_genre.created_at.strftime("%d %B %Y")
%td= link_to "(remove)", anime_genre, method: :delete, data: {confirm: "Are you sure?"}

app/views/anime_genres/_form.html.haml
= form_for @anime_genre, remote: true, html: { class: "form-inline" } do |f|
	- if @anime_genre.errors.any?
		.alert.alert-danger.alert-dismissable
			%button.close{type: "button", 'data-dismiss' => 'alert', 'alert-hidden' => 'true'} &times;
			%strong
				= pluralize(@anime_genre.errors.count, "error")
				prohibited this page from being saved:
			%ul
				- @anime_genre.errors.full_messages.each do |msg|
					%li= msg
	.form-group
		%label Name
		= f.text_field :name, class: "form-control"
	= f.submit "Submit", name: "submit", class: "btn btn-primary"

app/views/anime_genres/_sidebar.html.haml
.list-group
	= link_to posts_path, class: "list-group-item" do
		%span.badge= Post.all.count
		Movie
	= link_to siris_path, class: "list-group-item" do
		%span.badge= Siri.all.count
		TV Series
	= link_to animes_path, class: "list-group-item" do
		%span.badge= Anime.all.count
		Anime Series
	= link_to asians_path, class: "list-group-item" do
		%span.badge= Asian.all.count
		Asian Drama
	= link_to users_path, class: "list-group-item" do
		%span.badge= User.all.count
		User
	= link_to "Comment", "#", class: "list-group-item"
	= link_to genres_path, class: "list-group-item" do
		%span.badge= Genre.all.count
		Movie Genre
	= link_to siri_genres_path, class: "list-group-item" do
		%span.badge= SiriGenre.all.count
		TV Series Genre
	= link_to anime_genres_path, class: "list-group-item #{current_controller?(['anime_genres'])}" do
		%span.badge= AnimeGenre.all.count
		Anime Series Genre
	= link_to asian_genres_path, class: "list-group-item" do
		%span.badge= AsianGenre.all.count
		Asian Drama Genre

app/views/anime_genres/create.js.haml
:plain
	$('#new_anime_genre').remove();
	$('#new_anime').show();
	$('#all_anime_genre').append('#{j render(@anime_genre)}');

app/views/anime_genres/index.html.haml
- content_for :title do
	Kakitube.com | Anime Genre
- content_for :meta_tags do
	= render :partial => 'application/meta_tags', :locals => { :type => "website", :title => "KakiTube | Anime Genre", :url => request.url, :description => "KakiTube | Anime Genre", :canonical => request.url, :og_title => "KakiTube | Anime Genre", :og_description => "KakiTube | Anime Genre" }

/ Page Content
.container
	.row
		.col-lg-12
			.page-header
				%h1 Anime Genre List
	.row
		.col-md-4
			= render partial: "sidebar"
		.col-md-8
			#genre-list.panel.panel-default
				.panel-heading
					%h3.panel-title
						Anime Genre List
				.panel-body
					= link_to "New Anime Genre", new_anime_genre_path, id: "new_anime", remote: true
					%hr
					%table.table.table-bordered.table-hovered
						%thead
							%tr
								%th Name
								%th.col-md-2 Date Added
								%th.col-md-2 Action
						%tbody
							- @anime_genres.each do |anime_genre|
								%tr{id: "all_anime_genre"}
								%tr
									%td= anime_genre.name
									%td= anime_genre.created_at.strftime("%d %B %Y")
									%td= link_to "(remove)", anime_genre, method: :delete, data: {confirm: "Are you sure?"}
				/ .panel-footer

app/views/anime_genres/new.html.haml
= render partial: "form"

app/views/anime_genres/new.js.haml
:plain
	$('#new_anime').hide().after('#{j render("form")}');