config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
    get '/login' => 'devise/sessions#new'
    get '/register' => 'devise/registrations#new'
    get '/account_update' => 'devise/registrations#edit'
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do

      get 'movies' => 'pages#movies'

      get 'tv-series' => 'pages#series'

      get 'movies/:id' => 'pages#show'

      get 'tv-series/:id' => 'pages#view'

    end
  end

  resources :activities
  resources :posts
  resources :genres, except: [:show, :edit, :post]
  resources :siri_genres, except: [:show, :edit, :post]
  resources :anime_genres, except: [:show, :edit, :post]
  resources :asian_genres, except: [:show, :edit, :post]
  resources :users, except: [:show, :edit, :post, :destroy, :new, :create] do
    member do
      patch :revoke
      patch :grant
    end
  end
  resources :siris do
    resources :seasons, except: [:show] do
      resources :episodes
    end
  end
  resources :animes do
    resources :anime_seasons, except: [:show] do
      resources :anime_episodes
    end
  end
  resources :asians do
    resources :asian_seasons, except: [:show] do
      resources :asian_episodes
    end
  end
  resources :requests, only: [:new, :create, :show] do
    member do
      patch :set_pending
      patch :set_approved
      patch :set_rejected
      patch :set_closed
    end
  end
  resources :reports, only: [:new, :create, :show] do
    member do
      patch :mark_pending
      patch :mark_solved
    end
  end
  resources :bookmarks, only: [:create, :destroy]

  get '/dashboard' => 'dashboards#index'

  get 'movies/:sort/:id' => 'pages#show', as: 'genre_show'
  get 'tv-series/:view/:id' => 'pages#view', as: 'siri_genre_show'
  get '/tv-series/:view/:siri_id/:season_id-:id' => 'pages#ep', as: 'watch_ep'
  get 'anime-series/:anime_view/:id' => 'pages#anime_view', as: 'anime_genre_show'
  get '/anime-series/:anime_view/:anime_id/:anime_season_id-:id' => 'pages#anime_ep', as: 'watch_anime_ep'
  get 'asian-drama/:asian_view/:id' => 'pages#asian_view', as: 'asian_genre_show'
  get '/asian-drama/:asian_view/:asian_id/:asian_season_id-:id' => 'pages#asian_ep', as: 'watch_asian_ep'

  get '/developer' => 'pages#developer'
  get '/dmca' => 'pages#dmca'

  scope :q do
    get 'search' => 'pages#search', as: :search
  end

  get 'movies' => 'pages#movies'
  get 'movies/:sort/' => 'pages#movies', as: 'genre_index'
  get 'tv-series' => 'pages#series'
  get 'tv-series/:view/' => 'pages#series', as: 'siri_genre_index'
  get 'anime-series' => 'pages#anime_series'
  get 'anime-series/:anime_view/' => 'pages#anime_series', as: 'anime_genre_index'
  get 'asian-drama' => 'pages#asian_series'
  get 'asian-drama/:asian_view/' => 'pages#asian_series', as: 'asian_genre_index'

  get 'movies/all/page/:page' => 'pages#movies'
  get 'movies/:sort/page/:page' => 'pages#movies'
  get 'tv-series/all/page/:page' => 'pages#series'
  get 'tv-series/:view/page/:page' => 'pages#series'
  get 'anime-series/all/page/:page' => 'pages#anime_series'
  get 'anime-series/:anime_view/page/:page' => 'pages#anime_series'
  get 'asian-drama/all/page/:page' => 'pages#asian_series'
  get 'asian-drama/:asian_view/page/:page' => 'pages#asian_series'

  root 'pages#index'

  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/anime_season.rb
# == Schema Information
#
# Table name: anime_seasons
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  anime_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_anime_seasons_on_anime_id  (anime_id)
#

class AnimeSeason < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: Proc.new{ |controller, model| controller.current_user }

  belongs_to :anime
  has_many :anime_episodes, dependent: :destroy

  validates_presence_of :title

  default_scope -> { order('anime_seasons.created_at ASC') }
end

app/controllers/anime_seasons_controller.rb
class AnimeSeasonsController < ApplicationController
  before_action :authenticate_user!
	before_filter :set_anime, only: [:index, :new, :create, :edit, :update, :destroy]
  before_filter :set_anime_season, only: [:edit, :update, :destroy]
  before_filter :admin_only

  def index
  	@anime_seasons = AnimeSeason.where(anime_id: @anime).to_a
  end

  def new
  	@anime_season ||= AnimeSeason.new
    render
  end

  def create
  	@anime_season = @anime.anime_seasons.new(anime_season_params)
  	if @anime_season.save
  		redirect_to anime_anime_seasons_path, notice: "New anime season has been created."
  	else
  		render 'new'
  	end
  end

  def edit
    if @anime_season
      render
    else
      redirect_to anime_anime_seasons_path, notice: "Sorry! Anime season not found"
    end
  end

  def update
    if @anime_season.update_attributes(anime_season_params)
      redirect_to anime_anime_seasons_path, notice: "Successfully updated anime season."
    else
      render 'edit'
    end
  end

  def destroy
    @anime_season.destroy
    redirect_to anime_anime_seasons_path, notice: "Successfully destroyed anime season."
  end

  private

  def set_anime
  	@anime = Anime.find(params[:anime_id])
  end

  def set_anime_season
  	@anime_season = AnimeSeason.where(id: params[:id], anime: @anime).take
  end

  def anime_season_params
  	params.require(:anime_season).permit(:anime_id, :title)
  end
end

app/helpers/anime_seasons_helper.rb
module AnimeSeasonsHelper
end

app/views/anime_seasons/_sidebar.html.haml
.list-group
	= link_to posts_path, class: "list-group-item" do
		%span.badge= Post.all.count
		Movie
	= link_to siris_path, class: "list-group-item #{current_controller?(['seasons'])}" do
		%span.badge= Siri.all.count
		Series
	= link_to users_path, class: "list-group-item" do
		%span.badge= User.all.count
		User
	= link_to "Comment", "#", class: "list-group-item"
	= link_to genres_path, class: "list-group-item" do
		%span.badge= Genre.all.count
		Genre

app/views/anime_seasons/edit.html.haml
- content_for :title do
	Kakitube.com | Edit #{@anime.title} - #{@anime_season.title}
- content_for :meta_tags do
	= render :partial => 'application/meta_tags', :locals => { :type => "website", :title => "KakiTube | Edit #{@anime.title} - #{@anime_season.title}", :url => request.url, :description => "KakiTube | Edit #{@anime.title} - #{@anime_season.title}", :canonical => request.url, :og_title => "KakiTube | Edit #{@anime.title} - #{@anime_season.title}", :og_description => "KakiTube | Edit #{@anime.title} - #{@anime_season.title}" }

/ Page Content
.container
	.row
		.col-lg-12
			.page-header
				%h1 Edit #{@anime.title} - #{@anime_season.title}
	.row
		.col-md-4
			= render partial: "sidebar"
		.col-md-8
			#series-list.panel.panel-default
				.panel-heading
					%h3.panel-title #{@anime.title} - #{@anime_season.title}
				= form_for @anime_season, url: anime_anime_season_path, multipart: true, html: { class: "form-horizontal" } do |f|
					.panel-body
						- if @anime_season.errors.any?
							.alert.alert-danger.alert-dismissable
								%button.close{type: "button", 'data-dismiss' => 'alert', 'alert-hidden' => 'true'} &times;
								%strong
									= pluralize(@anime_season.errors.count, "error")
									prohibited this page from being saved:
								%ul
									- @anime_season.errors.full_messages.each do |msg|
										%li= msg
						.row
							.col-md-12
								.form-group
									= f.label :title, "Season Title", class: "col-sm-2 control-label"
									.col-sm-10
										= f.text_field :title, :class => "form-control"
					.panel-footer
						= f.submit "Save", :class => "btn btn-primary"
						= link_to "Cancel", anime_anime_seasons_path, class: "btn btn-default"

app/views/anime_seasons/index.html.haml
- content_for :title do
	Kakitube.com | Season List for #{@anime.title}
- content_for :meta_tags do
	= render :partial => 'application/meta_tags', :locals => { :type => "website", :title => "KakiTube | Season List for #{@anime.title}", :url => request.url, :description => "KakiTube | Season List for #{@anime.title}", :canonical => request.url, :og_title => "KakiTube | Season List for #{@anime.title}", :og_description => "KakiTube | Season List for #{@anime.title}" }

/ Page Content
.container
	.row
		.col-lg-12
			.page-header
				%h1 Seasons List for #{@anime.title}
	.row
		.col-md-4
			= render partial: "sidebar"
		.col-md-8
			.panel.panel-default
				.panel-heading
					%h3.panel-title
						Season list for #{@anime.title} #{link_to "Add new season", new_anime_anime_season_path, class: "btn btn-xs btn-primary pull-right", style: "color:#FFFFFF;"}
				#series-list.panel-body
					%table.table.table-bordered.table-hovered.display{id: "postLists"}
						%thead
							%tr
								%th Season Title
								%th Episode
								%th.col-md-3 Date Added
								%th.col-md-2 Action
						%tbody
							- @anime_seasons.each do |season|
								%tr
									%td= season.title
									%td= link_to pluralize(season.anime_episodes.size, "Episode"), anime_anime_season_anime_episodes_path(@anime, season), class: "btn btn-link"
									%td= season.created_at.strftime("%d %B %Y")
									%td
										.btn-group.btn-group-justified.btn-group-xs
											= link_to edit_anime_anime_season_path(@anime, season), class: "btn btn-default" do
												%span.glyphicon.glyphicon-edit{"aria-hidden" => true}
											= link_to anime_anime_season_path(@anime, season), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do
												%span.glyphicon.glyphicon-remove{"aria-hidden" => true}
				.panel-footer
					= link_to "Back", animes_path, class: "btn btn-default"

app/views/anime_seasons/new.html.haml
- content_for :title do
	Kakitube.com | Add New Season for #{@anime.title}
- content_for :meta_tags do
	= render :partial => 'application/meta_tags', :locals => { :type => "website", :title => "KakiTube | Add New Season for #{@anime.title}", :url => request.url, :description => "KakiTube | Add New Season for #{@anime.title}", :canonical => request.url, :og_title => "KakiTube | Add New Season for #{@anime.title}", :og_description => "KakiTube | Add New Season for #{@anime.title}" }

/ Page Content
.container
	.row
		.col-lg-12
			.page-header
				%h1 Add new season for #{@anime.title}
	.row
		.col-md-4
			= render partial: "sidebar"
		.col-md-8
			#series-list.panel.panel-default
				.panel-heading
					%h3.panel-title New season for #{@anime.title}
				= form_for @anime_season, url: anime_anime_seasons_path, multipart: true, html: { class: "form-horizontal" } do |f|
					.panel-body
						- if @anime_season.errors.any?
							.alert.alert-danger.alert-dismissable
								%button.close{type: "button", 'data-dismiss' => 'alert', 'alert-hidden' => 'true'} &times;
								%strong
									= pluralize(@anime_season.errors.count, "error")
									prohibited this page from being saved:
								%ul
									- @anime_season.errors.full_messages.each do |msg|
										%li= msg
						.row
							.col-md-12
								.form-group
									= f.label :title, "Season Title", class: "col-sm-2 control-label"
									.col-sm-10
										= f.text_field :title, :class => "form-control"
					.panel-footer
						= f.submit "Save", :class => "btn btn-primary"
						= link_to "Cancel", anime_anime_seasons_path, class: "btn btn-default"