config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
    get '/login' => 'devise/sessions#new'
    get '/register' => 'devise/registrations#new'
    get '/account_update' => 'devise/registrations#edit'
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do

      get 'movies' => 'pages#movies'

      get 'tv-series' => 'pages#series'

      get 'movies/:id' => 'pages#show'

      get 'tv-series/:id' => 'pages#view'

    end
  end

  resources :activities
  resources :posts
  resources :genres, except: [:show, :edit, :post]
  resources :siri_genres, except: [:show, :edit, :post]
  resources :anime_genres, except: [:show, :edit, :post]
  resources :asian_genres, except: [:show, :edit, :post]
  resources :users, except: [:show, :edit, :post, :destroy, :new, :create] do
    member do
      patch :revoke
      patch :grant
    end
  end
  resources :siris do
    resources :seasons, except: [:show] do
      resources :episodes
    end
  end
  resources :animes do
    resources :anime_seasons, except: [:show] do
      resources :anime_episodes
    end
  end
  resources :asians do
    resources :asian_seasons, except: [:show] do
      resources :asian_episodes
    end
  end
  resources :requests, only: [:new, :create, :show] do
    member do
      patch :set_pending
      patch :set_approved
      patch :set_rejected
      patch :set_closed
    end
  end
  resources :reports, only: [:new, :create, :show] do
    member do
      patch :mark_pending
      patch :mark_solved
    end
  end
  resources :bookmarks, only: [:create, :destroy]

  get '/dashboard' => 'dashboards#index'

  get 'movies/:sort/:id' => 'pages#show', as: 'genre_show'
  get 'tv-series/:view/:id' => 'pages#view', as: 'siri_genre_show'
  get '/tv-series/:view/:siri_id/:season_id-:id' => 'pages#ep', as: 'watch_ep'
  get 'anime-series/:anime_view/:id' => 'pages#anime_view', as: 'anime_genre_show'
  get '/anime-series/:anime_view/:anime_id/:anime_season_id-:id' => 'pages#anime_ep', as: 'watch_anime_ep'
  get 'asian-drama/:asian_view/:id' => 'pages#asian_view', as: 'asian_genre_show'
  get '/asian-drama/:asian_view/:asian_id/:asian_season_id-:id' => 'pages#asian_ep', as: 'watch_asian_ep'

  get '/developer' => 'pages#developer'
  get '/dmca' => 'pages#dmca'

  scope :q do
    get 'search' => 'pages#search', as: :search
  end

  get 'movies' => 'pages#movies'
  get 'movies/:sort/' => 'pages#movies', as: 'genre_index'
  get 'tv-series' => 'pages#series'
  get 'tv-series/:view/' => 'pages#series', as: 'siri_genre_index'
  get 'anime-series' => 'pages#anime_series'
  get 'anime-series/:anime_view/' => 'pages#anime_series', as: 'anime_genre_index'
  get 'asian-drama' => 'pages#asian_series'
  get 'asian-drama/:asian_view/' => 'pages#asian_series', as: 'asian_genre_index'

  get 'movies/all/page/:page' => 'pages#movies'
  get 'movies/:sort/page/:page' => 'pages#movies'
  get 'tv-series/all/page/:page' => 'pages#series'
  get 'tv-series/:view/page/:page' => 'pages#series'
  get 'anime-series/all/page/:page' => 'pages#anime_series'
  get 'anime-series/:anime_view/page/:page' => 'pages#anime_series'
  get 'asian-drama/all/page/:page' => 'pages#asian_series'
  get 'asian-drama/:asian_view/page/:page' => 'pages#asian_series'

  root 'pages#index'

  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/episode.rb
# == Schema Information
#
# Table name: episodes
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  season_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  embed      :text(65535)
#  embed2     :text(65535)
#  embed3     :text(65535)
#
# Indexes
#
#  index_episodes_on_season_id  (season_id)
#

class Episode < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: Proc.new{ |controller, model| controller.current_user }
  
  belongs_to :season, touch: true

  after_commit :updated_series

  validates_presence_of :title
  validates_presence_of :embed

  default_scope -> { order('episodes.created_at ASC') }

  private

  def updated_series
  	self.season.siri.touch(:updated_at)
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :authenticate_user!
	before_filter :set_season, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  before_filter :set_episode, only: [:show, :edit, :update, :destroy]
  before_filter :admin_only

  def index
  	@episodes = Episode.where(season_id: @season).to_a
  end

  def new
  	@episode ||= Episode.new
    render
  end

  def create
  	@episode = @season.episodes.new(episode_params)
  	if @episode.save
  		redirect_to siri_season_episodes_path, notice: "New episode has been created."
  	else
  		render 'new'
  	end
  end

  def show
    if @episode
      render
    else
      redirect_to siri_season_episodes_path, notice: "Sorry! Episode not found"
    end
  end

  def edit
    if @episode
      render
    else
      redirect_to siri_season_episodes_path, notice: "Sorry! Season not found"
    end
  end

  def update
    if @episode.update_attributes(episode_params)
      redirect_to siri_season_episodes_path, notice: "Successfully updated episode."
    else
      render 'edit'
    end
  end

  def destroy
    @episode.destroy
    redirect_to siri_season_episodes_path, notice: "Successfully destroyed episode."
  end

  private

  def set_season
  	@season = Season.find(params[:season_id])
  end

  def set_episode
  	@episode = Episode.where(id: params[:id], season: @season).take
  end

  def episode_params
  	params.require(:episode).permit(:season_id, :title, :embed, :embed2, :embed3)
  end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_form.html.haml
= form_for @episode, url: siri_season_episodes_path, html: { class: "form-horizontal" } do |f|
	.panel-body
		- if @episode.errors.any?
			.alert.alert-danger.alert-dismissable
				%button.close{type: "button", 'data-dismiss' => 'alert', 'alert-hidden' => 'true'} &times;
				%strong
					= pluralize(@episode.errors.count, "error")
					prohibited this page from being saved:
				%ul
					- @episode.errors.full_messages.each do |msg|
						%li= msg
		.row
			.col-md-12
				.form-group
					= f.label :title, "Episode Title", class: "col-sm-2 control-label"
					.col-sm-10
						= f.text_field :title, :class => "form-control"
				.form-group
					= f.label :embed, "Embed Code (source 1)", class: "col-sm-2 control-label"
					.col-sm-10
						= f.text_area :embed, :class => "form-control", rows: 5
				.form-group
					= f.label :embed2, "Embed Code (source 2)", class: "col-sm-2 control-label"
					.col-sm-10
						= f.text_area :embed2, :class => "form-control", rows: 5
				.form-group
					= f.label :embed3, "Embed Code (source 2)", class: "col-sm-2 control-label"
					.col-sm-10
						= f.text_area :embed3, :class => "form-control", rows: 5
	.panel-footer
		= f.submit "Save", :class => "btn btn-primary"
		= link_to "Cancel", siri_season_episodes_path, class: "btn btn-default"

app/views/episodes/edit.html.haml
- content_for :title do
	Kakitube.com | Edit #{@season.siri.title} - #{@season.title} - #{@episode.title}
- content_for :meta_tags do
	= render :partial => 'application/meta_tags', :locals => { :type => "website", :title => "KakiTube | Edit #{@season.siri.title} - #{@season.title} - #{@episode.title}", :url => request.url, :description => "KakiTube | Edit #{@season.siri.title} - #{@season.title} - #{@episode.title}", :canonical => request.url, :og_title => "KakiTube | Edit #{@season.siri.title} - #{@season.title} - #{@episode.title}", :og_description => "KakiTube | Edit #{@season.siri.title} - #{@season.title} - #{@episode.title}" }
	
/ Page Content
.container
	.row
		.col-lg-12
			.page-header
				%h1 Edit #{@season.siri.title} - #{@season.title} - #{@episode.title}
	.row
		.col-md-4
			= render partial: "sidebar"
		.col-md-8
			#series-list.panel.panel-default
				.panel-heading
					%h3.panel-title #{@season.siri.title} - #{@season.title} - #{@episode.title}
				= form_for @episode, url: siri_season_episode_path, html: { class: "form-horizontal" } do |f|
					.panel-body
						- if @episode.errors.any?
							.alert.alert-danger.alert-dismissable
								%button.close{type: "button", 'data-dismiss' => 'alert', 'alert-hidden' => 'true'} &times;
								%strong
									= pluralize(@episode.errors.count, "error")
									prohibited this page from being saved:
								%ul
									- @episode.errors.full_messages.each do |msg|
										%li= msg
						.row
							.col-md-12
								.form-group
									= f.label :title, "Episode Title", class: "col-sm-2 control-label"
									.col-sm-10
										= f.text_field :title, :class => "form-control"
								.form-group
									= f.label :embed, "Embed Code", class: "col-sm-2 control-label"
									.col-sm-10
										= f.text_area :embed, :class => "form-control", rows: 5
								.form-group
									= f.label :embed2, "Embed Code (source 2)", class: "col-sm-2 control-label"
									.col-sm-10
										= f.text_area :embed2, :class => "form-control", rows: 5
								.form-group
									= f.label :embed3, "Embed Code (source 2)", class: "col-sm-2 control-label"
									.col-sm-10
										= f.text_area :embed3, :class => "form-control", rows: 5
					.panel-footer
						= f.submit "Save", :class => "btn btn-primary"
						= link_to "Cancel", siri_season_episodes_path, class: "btn btn-default"

app/views/episodes/index.html.haml
- content_for :title do
	Kakitube.com | Episode List for #{@season.siri.title} #{@season.title}
- content_for :meta_tags do
	= render :partial => 'application/meta_tags', :locals => { :type => "website", :title => "KakiTube | Episode List for #{@season.siri.title} #{@season.title}", :url => request.url, :description => "KakiTube | Episode List for #{@season.siri.title} #{@season.title}", :canonical => request.url, :og_title => "KakiTube | Episode List for #{@season.siri.title} #{@season.title}", :og_description => "KakiTube | Episode List for #{@season.siri.title} #{@season.title}" }
	
/ Page Content
.container
	.row
		.col-lg-12
			.page-header
				%h1 Episode List for #{@season.siri.title} #{@season.title}
	.row
		.col-md-4
			= render partial: "sidebar"
		.col-md-8
			.panel.panel-default
				.panel-heading
					%h3.panel-title
						Episode List for #{@season.siri.title} #{@season.title} #{link_to "Add new episode", new_siri_season_episode_path, class: "btn btn-xs btn-primary pull-right", style: "color:#FFFFFF;"}
				#series-list.panel-body
					%table.table.table-bordered.table-hovered.display{id: "postLists"}
						%thead
							%tr
								%th Episode Title
								%th.col-md-3 Date Added
								%th.col-md-2 Action
						%tbody
							- @episodes.each do |episode|
								%tr
									%td= episode.title
									%td= episode.created_at.strftime("%d %B %Y")
									%td
										.btn-group.btn-group-justified.btn-group-xs
											= link_to siri_season_episode_path(@season.siri, @season, episode), class: "btn btn-primary" do
												%span.glyphicon.glyphicon-eye-open{"aria-hidden" => true}
											= link_to edit_siri_season_episode_path(@season.siri, @season, episode), class: "btn btn-default" do
												%span.glyphicon.glyphicon-edit{"aria-hidden" => true}
											= link_to siri_season_episode_path(@season.siri, @season, episode), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do
												%span.glyphicon.glyphicon-remove{"aria-hidden" => true}
				.panel-footer
					= link_to "Back", siri_seasons_path, class: "btn btn-default"

app/views/episodes/new.html.haml
- content_for :title do
	Kakitube.com | Add New Episode for #{@season.siri.title} #{@season.title}
- content_for :meta_tags do
	= render :partial => 'application/meta_tags', :locals => { :type => "website", :title => "KakiTube | Add New Episode for #{@season.siri.title} #{@season.title}", :url => request.url, :description => "KakiTube | Add New Episode for #{@season.siri.title} #{@season.title}", :canonical => request.url, :og_title => "KakiTube | Add New Episode for #{@season.siri.title} #{@season.title}", :og_description => "KakiTube | Add New Episode for #{@season.siri.title} #{@season.title}" }
	
/ Page Content
.container
	.row
		.col-lg-12
			.page-header
				%h1 Add New Episode for #{@season.siri.title} #{@season.title}
	.row
		.col-md-4
			= render partial: "sidebar"
		.col-md-8
			#series-list.panel.panel-default
				.panel-heading
					%h3.panel-title Add New Episode for #{@season.siri.title} #{@season.title}
				= render "form"

app/views/episodes/show.html.haml
- content_for :title do
	Kakitube.com | TV Series List
- content_for :meta_tags do
	= render :partial => 'application/meta_tags', :locals => { :type => "website", :title => "KakiTube | TV Series List", :url => request.url, :description => "KakiTube", :canonical => request.url, :og_title => "KakiTube | TV Series List", :og_description => "KakiTube" }

/ Page Content
.container
	.row
		.col-lg-12
			.page-header
				%h1= @episode.title
	.row
		.col-md-4
			= render partial: "sidebar"
		.col-md-8
			%h2 #{@season.siri.title} - #{@season.title} - #{@episode.title}
			%hr
			.embed-responsive.embed-responsive-16by9
				.embed-responsive-item= @episode.embed.html_safe
			%hr
			= link_to 'Edit this episode', edit_siri_season_episode_path(@season.siri, @season, @episode), class: "btn btn-primary"
			= link_to 'Back to Episode list', siri_season_episodes_path, class: "btn btn-default"