config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
    get '/login' => 'devise/sessions#new'
    get '/register' => 'devise/registrations#new'
    get '/account_update' => 'devise/registrations#edit'
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do

      get 'movies' => 'pages#movies'

      get 'tv-series' => 'pages#series'

      get 'movies/:id' => 'pages#show'

      get 'tv-series/:id' => 'pages#view'

    end
  end

  resources :activities
  resources :posts
  resources :genres, except: [:show, :edit, :post]
  resources :siri_genres, except: [:show, :edit, :post]
  resources :anime_genres, except: [:show, :edit, :post]
  resources :asian_genres, except: [:show, :edit, :post]
  resources :users, except: [:show, :edit, :post, :destroy, :new, :create] do
    member do
      patch :revoke
      patch :grant
    end
  end
  resources :siris do
    resources :seasons, except: [:show] do
      resources :episodes
    end
  end
  resources :animes do
    resources :anime_seasons, except: [:show] do
      resources :anime_episodes
    end
  end
  resources :asians do
    resources :asian_seasons, except: [:show] do
      resources :asian_episodes
    end
  end
  resources :requests, only: [:new, :create, :show] do
    member do
      patch :set_pending
      patch :set_approved
      patch :set_rejected
      patch :set_closed
    end
  end
  resources :reports, only: [:new, :create, :show] do
    member do
      patch :mark_pending
      patch :mark_solved
    end
  end
  resources :bookmarks, only: [:create, :destroy]

  get '/dashboard' => 'dashboards#index'

  get 'movies/:sort/:id' => 'pages#show', as: 'genre_show'
  get 'tv-series/:view/:id' => 'pages#view', as: 'siri_genre_show'
  get '/tv-series/:view/:siri_id/:season_id-:id' => 'pages#ep', as: 'watch_ep'
  get 'anime-series/:anime_view/:id' => 'pages#anime_view', as: 'anime_genre_show'
  get '/anime-series/:anime_view/:anime_id/:anime_season_id-:id' => 'pages#anime_ep', as: 'watch_anime_ep'
  get 'asian-drama/:asian_view/:id' => 'pages#asian_view', as: 'asian_genre_show'
  get '/asian-drama/:asian_view/:asian_id/:asian_season_id-:id' => 'pages#asian_ep', as: 'watch_asian_ep'

  get '/developer' => 'pages#developer'
  get '/dmca' => 'pages#dmca'

  scope :q do
    get 'search' => 'pages#search', as: :search
  end

  get 'movies' => 'pages#movies'
  get 'movies/:sort/' => 'pages#movies', as: 'genre_index'
  get 'tv-series' => 'pages#series'
  get 'tv-series/:view/' => 'pages#series', as: 'siri_genre_index'
  get 'anime-series' => 'pages#anime_series'
  get 'anime-series/:anime_view/' => 'pages#anime_series', as: 'anime_genre_index'
  get 'asian-drama' => 'pages#asian_series'
  get 'asian-drama/:asian_view/' => 'pages#asian_series', as: 'asian_genre_index'

  get 'movies/all/page/:page' => 'pages#movies'
  get 'movies/:sort/page/:page' => 'pages#movies'
  get 'tv-series/all/page/:page' => 'pages#series'
  get 'tv-series/:view/page/:page' => 'pages#series'
  get 'anime-series/all/page/:page' => 'pages#anime_series'
  get 'anime-series/:anime_view/page/:page' => 'pages#anime_series'
  get 'asian-drama/all/page/:page' => 'pages#asian_series'
  get 'asian-drama/:asian_view/page/:page' => 'pages#asian_series'

  root 'pages#index'

  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/anime.rb
# == Schema Information
#
# Table name: animes
#
#  id              :integer          not null, primary key
#  title           :string(255)
#  slug            :string(255)
#  status          :string(255)
#  user_id         :integer
#  imdbID          :string(255)
#  year            :integer
#  rated           :string(255)
#  released        :string(255)
#  runtime         :string(255)
#  director        :string(255)
#  writer          :string(255)
#  actors          :string(255)
#  language        :string(255)
#  country         :string(255)
#  awards          :string(255)
#  poster          :string(255)
#  metascore       :string(255)
#  imdbrating      :string(255)
#  imdbvotes       :string(255)
#  description     :text(65535)
#  anime_genre_id  :integer
#  gallery_image_1 :string(255)
#  gallery_image_2 :string(255)
#  gallery_image_3 :string(255)
#  header_image    :string(255)
#  bg_image        :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_animes_on_anime_genre_id  (anime_genre_id)
#  index_animes_on_slug            (slug) UNIQUE
#  index_animes_on_user_id         (user_id)
#

class Anime < ActiveRecord::Base
  mount_uploader :poster, PosterUploader
  mount_uploader :header_image, HeaderImageUploader
  mount_uploader :gallery_image_1, GalleryImage1Uploader
  mount_uploader :gallery_image_2, GalleryImage2Uploader
  mount_uploader :gallery_image_3, GalleryImage3Uploader
  process_in_background :poster
  process_in_background :header_image
  process_in_background :gallery_image_1
  process_in_background :gallery_image_2
  process_in_background :gallery_image_3

  include PublicActivity::Model
  tracked owner: Proc.new{ |controller, model| controller.current_user }

  belongs_to :user
  has_many :anime_seasons, dependent: :destroy
  belongs_to :anime_genre
  has_many :bookmarks, as: :bookmarkable, dependent: :destroy

	accepts_nested_attributes_for :bookmarks, allow_destroy: true

  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders, :history]
  default_scope -> { order('animes.updated_at DESC') }
  scope :by_anime_genre, -> (anime_genre_id) { where(anime_genre_id: anime_genre_id) }
  scope :latest_update, -> { unscope(:order).order('`animes`.updated_at DESC') }
  scope :random, -> { unscope(:order).order('RAND()') }

  searchable do
    text :title, boost: 5
    text :description
  end

  validates_presence_of :title
  validates_presence_of :year
  validates_presence_of :released
  validates_presence_of :runtime
  validates_presence_of :director
  validates_presence_of :writer
  validates_presence_of :actors
  validates_presence_of :description
  validates_presence_of :language
  validates_presence_of :country
  validates_presence_of :poster
  validates_presence_of :header_image

  def is_on_going?
    status === "On-Going"
  end

  def is_completed?
    status === "Completed"
  end
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  before_action :authenticate_user!
	before_filter :set_user, only: [:new, :create]
	before_filter :set_anime, only: [:show, :edit, :update, :destroy]
  before_filter :admin_only
  include HTTParty

  def index
  	@animes = Anime.all
  end

  def show
  	if @anime
      respond_to do |format|
        format.html { @anime }
        format.json { render json: @anime.to_json(include: [:user]) }
      end
    else
      redirect_to animes_path, notice: "Sorry! Anime not found"
    end
  end

  def new
  	@anime ||= Anime.new
  	render
  end

  def create
  	@anime = @user.animes.new(anime_params)
    if params[:preview_button]
      url = "http://www.omdbapi.com/?i=#{@anime.imdbID}&plot=full&r=json"
      @response = HTTParty.get(URI.encode(url))
      @result = JSON.parse(@response.body)
      @anime.title = @result["Title"]
      @anime.year = @result["Year"]
      @anime.rated = @result["Rated"]
      @anime.released = @result["Released"]
      @anime.runtime = @result["Runtime"]
      @anime.director = @result["Director"]
      @anime.writer = @result["Writer"]
      @anime.actors = @result["Actors"]
      @anime.description = @result["Plot"]
      @anime.language = @result["Language"]
      @anime.country = @result["Country"]
      @anime.metascore = @result["Metascore"]
      @anime.imdbrating = @result["imdbRating"]
      @anime.imdbvotes = @result["imdbVotes"]
      render 'new'
    elsif params[:submit]
    	if @anime.save
        expire_fragment("latest-anime-update")
        expire_fragment("anime-list")
        redirect_to animes_path, notice: "Successfully created anime."
      else
        render 'new'
      end
    end
  end

  def edit
    if @anime
      render
    else
      redirect_to animes_path, notice: "Sorry! Anime not found"
    end
  end

  def update
    if @anime.update_attributes(anime_params)
      expire_fragment("latest-anime-update")
      expire_fragment("anime-list")
      redirect_to animes_path, notice: "Successfully updated anime."
    else
      render 'edit'
    end
  end

  def destroy
    @anime.destroy
    redirect_to animes_path, notice: "Successfully destroyed anime."
  end

  private

  def set_user
  	@user = current_user
  end

  def set_anime
    @anime = Anime.find(params[:id])
  end

  def anime_params
  	params.require(:anime).permit(:title, :status, :imdbID, :poster, :poster_cache, :header_image, :header_image_cache, :year, :rated, :released, :runtime, :description, :director, :writer, :actors, :language, :country, :anime_genre_id, :awards, :metascore, :imdbrating, :imdbvotes, :gallery_image_1, :gallery_image_1_cache, :gallery_image_2, :gallery_image_2_cache, :gallery_image_3, :gallery_image_3_cache)
  end
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/views/animes/_form.html.haml
= form_for @anime, multipart: true, html: { class: "form-horizontal" } do |f|
	.panel-body
		- if @anime.errors.any?
			.alert.alert-danger.alert-dismissable
				%button.close{type: "button", 'data-dismiss' => 'alert', 'alert-hidden' => 'true'} &times;
				%strong
					= pluralize(@anime.errors.count, "error")
					prohibited this page from being saved:
				%ul
					- @anime.errors.full_messages.each do |msg|
						%li= msg
		.row
			.col-md-6
				.form-group
					= f.label :imdbID, "IMDB ID", class: "col-sm-2 control-label"
					.col-sm-10
						.input-group
							= f.text_field :imdbID, class: "form-control"
							%span.input-group-btn
								= f.submit "Fetch Data", name: "preview_button", class: "btn btn-primary"
						%p.help-block.small Leave blank if you are not fetching the data from IMDB
				%hr
				.form-group
					= f.label :poster, "Poster", class: "col-sm-2 control-label"
					.col-sm-10
						- if @anime.try(:poster?)
							= image_tag(@anime.poster_url(:standard), class: "img-responsive")
						- else
							= image_tag('poster-default.png', class: "img-responsive")
						%h6 Replace current image
						= f.file_field :poster, class: "form-control"
						= f.hidden_field :poster_cache
				.form-group
					= f.label :header_image, "Header Image", class: "col-sm-2 control-label"
					.col-sm-10
						- if @anime.try(:header_image?)
							= image_tag(@anime.header_image_url(:standard), class: "img-responsive")
						- else
							= image_tag('poster-latest.png', class: "img-responsive")
						%h6 Replace current image
						= f.file_field :header_image, class: "form-control"
						= f.hidden_field :header_image_cache
				.form-group
					= f.label :title, "Anime Name", class: "col-sm-2 control-label"
					.col-sm-10
						= f.text_field :title, class: "form-control", placeholder: "Anime Name"
				.row
					.col-md-6
						.form-group
							= f.label :year, "Year", class: "col-sm-4 control-label"
							.col-sm-8
								= f.text_field :year, class: "form-control", placeholder: "1999"
					.col-md-6
						.form-group
							= f.label :rated, "Rated", class: "col-sm-4 control-label"
							.col-sm-8
								= f.select(:rated, options_for_select([['TV-Y - All Chidren', 'TV-Y'], ['TV-Y7 - Directed to Older Children', 'TV-Y7'], ['TV-Y7-FV - Directed to Older Children - Fantasy Violence', 'TV-Y7-FV'], ['TV-G - General Audience', 'TV-G'], ['TV-PG Parental Guidance Suggested', 'TV-PG'], ['TV-14 - Parents Strongly Cautioned', 'TV-14'], ['TV-MA - Mature Audience Only', 'TV-MA']], @anime.rated), {}, {:class => "form-control"})
				.row
					.col-md-6
						.form-group
							= f.label :released, "Released", class: "col-sm-4 control-label"
							.col-sm-8
								= f.text_field :released, class: "form-control", placeholder: "01 Sept 1999"
					.col-md-6
						.form-group
							= f.label :runtime, "Runtime", class: "col-sm-4 control-label"
							.col-sm-8
								= f.text_field :runtime, class: "form-control", placeholder: "120 min"
				.form-group
					= f.label :director, "Director", class: "col-sm-2 control-label"
					.col-sm-10
						= f.text_field :director, class: "form-control"
				.form-group
					= f.label :writer, "Writer", class: "col-sm-2 control-label"
					.col-sm-10
						= f.text_field :writer, class: "form-control"
				.form-group
					= f.label :actors, "Actors", class: "col-sm-2 control-label"
					.col-sm-10
						= f.text_field :actors, class: "form-control"
				.form-group
					= f.label :description, "Description", class: "col-sm-2 control-label"
					.col-sm-10
						= f.text_area :description, class: "form-control", rows: 8
				.row
					.col-md-6
						.form-group
							= f.label :language, "Language", class: "col-sm-4 control-label"
							.col-sm-8
								= f.text_field :language, class: "form-control", placeholder: "English, Chinese"
					.col-md-6
						.form-group
							= f.label :country, "Country", class: "col-sm-4 control-label"
							.col-sm-8
								= f.text_field :country, class: "form-control", placeholder: "USA"
				.form-group
					= f.label :anime_genre_id, "Genre", class: "col-md-2 control-label"
					.col-md-10
						= f.collection_select :anime_genre_id, AnimeGenre.order(:name), :id, :name, {}, :class => "form-control"
				.form-group
					= f.label :status, "Status", class: "col-sm-2 control-label"
					.col-sm-10
						= f.select(:status, options_for_select([['On-Going', 'On-Going'], ['Completed', 'Completed']], @anime.status), {}, {:class => "form-control"})
				.row
					%h3.col-md-12
						%strong Gallery Image
					.col-md-4
						.form-group
							= f.label :gallery_image_1, "Image 1", class: "col-sm-4 control-label"
							.col-sm-8
								- if @anime.try(:gallery_image_1?)
									= image_tag(@anime.gallery_image_1_url(:standard), class: "img-responsive")
								- else
									= image_tag('poster-default.png', class: "img-responsive")
								%h6 Replace current image
								= f.file_field :gallery_image_1, class: "form-control"
								= f.hidden_field :gallery_image_1_cache
					.col-md-4
						.form-group
							= f.label :gallery_image_2, "Image 2", class: "col-sm-4 control-label"
							.col-sm-8
								- if @anime.try(:gallery_image_2?)
									= image_tag(@anime.gallery_image_2_url(:standard), class: "img-responsive")
								- else
									= image_tag('poster-default.png', class: "img-responsive")
								%h6 Replace current image
								= f.file_field :gallery_image_2, class: "form-control"
								= f.hidden_field :gallery_image_2_cache
					.col-md-4
						.form-group
							= f.label :gallery_image_3, "Image 3", class: "col-sm-4 control-label"
							.col-sm-8
								- if @anime.try(:gallery_image_3?)
									= image_tag(@anime.gallery_image_3_url(:standard), class: "img-responsive")
								- else
									= image_tag('poster-default.png', class: "img-responsive")
								%h6 Replace current image
								= f.file_field :gallery_image_3, class: "form-control"
								= f.hidden_field :gallery_image_3_cache
			= f.hidden_field :metascore, class: "form-control"
			= f.hidden_field :imdbrating, class: "form-control"
			= f.hidden_field :imdbvotes, class: "form-control"
			.col-md-6
				- if params[:preview_button]
					#preview
						%pre= JSON.pretty_generate(@result)
	.panel-footer
		= f.submit "Submit", name: "submit", class: "btn btn-primary"
		= link_to "Cancel", animes_path, class: "btn btn-link"

app/views/animes/_sidebar.html.haml
.list-group
	= link_to posts_path, class: "list-group-item" do
		%span.badge= Post.all.count
		Movie
	= link_to siris_path, class: "list-group-item" do
		%span.badge= Siri.all.count
		TV Series
	= link_to animes_path, class: "list-group-item #{current_controller?(['animes'])}" do
		%span.badge= Anime.all.count
		Anime Series
	= link_to asians_path, class: "list-group-item" do
		%span.badge= Asian.all.count
		Asian Drama
	= link_to users_path, class: "list-group-item" do
		%span.badge= User.all.count
		User
	= link_to "Comment", "#", class: "list-group-item"
	= link_to genres_path, class: "list-group-item" do
		%span.badge= Genre.all.count
		Movie Genre
	= link_to siri_genres_path, class: "list-group-item" do
		%span.badge= SiriGenre.all.count
		TV Series Genre
	= link_to anime_genres_path, class: "list-group-item" do
		%span.badge= AnimeGenre.all.count
		Anime Series Genre
	= link_to asian_genres_path, class: "list-group-item" do
		%span.badge= AsianGenre.all.count
		Asian Drama Genre

app/views/animes/edit.html.haml
- content_for :title do
	Kakitube.com | Edit Anime
- content_for :meta_tags do
	= render :partial => 'application/meta_tags', :locals => { :type => "website", :title => "KakiTube | Edit Anime", :url => request.url, :description => "KakiTube", :canonical => request.url, :og_title => "KakiTube | Edit Anime", :og_description => "KakiTube" }

/ Page Content
.container
	.row
		.col-lg-12
			.page-header
				%h1 Edit Anime
			#series-list.panel.panel-default
				.panel-heading
					%h3.panel-title Edit Anime
				= render "form"

app/views/animes/index.html.haml
- content_for :title do
	Kakitube.com | Anime List
- content_for :meta_tags do
	= render :partial => 'application/meta_tags', :locals => { :type => "website", :title => "KakiTube | Anime List", :url => request.url, :description => "KakiTube", :canonical => request.url, :og_title => "KakiTube | Anime List", :og_description => "KakiTube" }

/ Page Content
.container
	.row
		.col-lg-12
			.page-header
				%h1 Anime List
	.row
		.col-md-4
			= render partial: "sidebar"
		.col-md-8
			.panel.panel-default
				.panel-heading
					%h3.panel-title
						Anime List #{link_to "Add new anime", new_anime_path, class: "btn btn-xs btn-primary pull-right", style: "color:#FFFFFF;"}
				#series-list.panel-body
					%table.table.table-bordered.table-hovered.display{id: "postLists"}
						%thead
							%tr
								%th Anime Title
								%th Season
								%th.col-md-3 Date Added
								%th Status
								%th.col-md-2 Action
						%tbody
							- @animes.each do |anime|
								%tr
									%td= anime.title
									%td= link_to pluralize(anime.anime_seasons.size, "Season"), anime_anime_seasons_path(anime), class: "btn btn-link"
									%td= anime.created_at.strftime("%d %B %Y")
									%td
										- if anime.is_on_going?
											%span.label.label-warning
												= anime.status
										- elsif anime.is_completed?
											%span.label.label-primary
												= anime.status
									%td
										.btn-group.btn-group-justified.btn-group-xs
											= link_to anime_path(anime), class: "btn btn-primary" do
												%span.glyphicon.glyphicon-eye-open{"aria-hidden" => true}
											= link_to edit_anime_url(anime), class: "btn btn-default" do
												%span.glyphicon.glyphicon-edit{"aria-hidden" => true}
											= link_to anime_path(anime), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do
												%span.glyphicon.glyphicon-remove{"aria-hidden" => true}

app/views/animes/new.html.haml
- content_for :title do
	Kakitube.com | Add New Anime
- content_for :meta_tags do
	= render :partial => 'application/meta_tags', :locals => { :type => "website", :title => "KakiTube | New Anime", :url => request.url, :description => "KakiTube", :canonical => request.url, :og_title => "KakiTube | New Anime", :og_description => "KakiTube" }

/ Page Content
.container
	.row
		.col-lg-12
			.page-header
				%h1 Add New Anime
			#series-list.panel.panel-default
				.panel-heading
					%h3.panel-title New Anime Form
				= render "form"

app/views/animes/show.html.haml
- content_for :title do
	Kakitube.com | Anime
- content_for :meta_tags do
	= render :partial => 'application/meta_tags', :locals => { :type => "website", :title => "KakiTube | Anime", :url => request.url, :description => "KakiTube", :canonical => request.url, :og_title => "KakiTube | Anime", :og_description => "KakiTube" }

/ Page Content
.container
	.row
		.col-lg-12
			.page-header
				%h1 Anime
	.row
		.col-md-4
			= render partial: "sidebar"
		.col-md-8
			%h2= @anime.title
			%p
				Genre
				%span.label.label-primary #{@anime.anime_genre.name}
				- if @anime.is_on_going?
					%span.label.label-warning
						= @anime.status
				- elsif @anime.is_completed?
					%span.label.label-primary
						= @anime.status
			.row
				.col-md-4
					= image_tag(@anime.poster_url(:standard), class: "img-responsive")
				.col-md-8
					%p
						= @anime.description
					.row
						.col-md-6
							%p
								%strong Director
								%p= @anime.director
						.col-md-6
							%p
								%strong Actors
								%p= @anime.actors
					.row
						.col-md-6
							%p
								%strong Language
								%p= @anime.language
						.col-md-6
							%p
								%strong Country
								%p= @anime.country
					.row
						.col-md-4
							%p
								%strong Metascore
								%p
									%span.label.label-default
										%span.glyphicon.glyphicon-stats
										= @anime.metascore? ? @anime.metascore : "N/A"
						.col-md-4
							%p
								%strong IMDB Rating
								%p
									%span.label.label-default
										%span.glyphicon.glyphicon-heart
										= @anime.imdbrating? ? @anime.imdbrating : "N/A"
						.col-md-4
							%p
								%strong IMDB Votes
								%p
									%span.label.label-default
										%span.glyphicon.glyphicon-thumbs-up
										= @anime.imdbvotes? ? @anime.imdbvotes : "N/A"
					%table.table.table-bordered
						%tbody
							%tr
								%td.col-md-3
									%center
										%strong Year
										%br/
										%span.label.label-default= @anime.year
								%td.col-md-3
									%center
										%strong Rated
										%br/
										%span.label.label-default= @anime.rated
								%td.col-md-3
									%center
										%strong Released
										%br/
										%span.label.label-default= @anime.released
								%td.col-md-3
									%center
										%strong Runtime
										%br/
										%span.label.label-default= @anime.runtime
			%hr
			%h4 Gallery Image
			.row
				.col-md-4
					= image_tag(@anime.gallery_image_1_url(:standard), class: "thumbnail img-responsive")
				.col-md-4
					= image_tag(@anime.gallery_image_2_url(:standard), class: "thumbnail img-responsive")
				.col-md-4
					= image_tag(@anime.gallery_image_3_url(:standard), class: "thumbnail img-responsive")
			%hr
			#accordian.panel-group{role: "tablist", "aria-multiselectable" => true}
				- @anime.anime_seasons.each do |season|
					.panel.panel-default
						.panel-heading{role: "tab", id: "#{season.title}"}
							%a{"data-toggle" => "collapse", "data-parent" => "#accordion", href: "##{season.id}", "aria-expanded" => true, "aria-controls" => "#{season.id}"}
								%h4.panel-title
									= season.title
									.pull-right
										%p.small Total Episodes: #{season.asian_episodes.count}
						.panel-collapse.collapse{role: "tabpanel", "aria-labelledby" => "#{season.title}", id: "#{season.id}"}
							#episode-list.panel-body
								%table.table.table-bordered.table-hovered
									- season.anime_episodes.each do |episode|
										%tr
											%td
												= episode.title
												.pull-right
													%button{"data-toggle" => "modal", "data-target" => "#episode-#{episode.id}", class: "btn btn-link btn-xs"}
														%span.glyphicon.glyphicon-play-circle
														Watch Now
												.modal.fade.cls{tabindex: -1, role: "dialog", "aria-labelledby" => "Video", "aria-hidden" => true, id: "episode-#{episode.id}"}
													.modal-dialog
														.modal-content
															.modal-header
																%button.close{type: "button", "data-dismiss" => "modal", "aria-label" => "Close"}
																	%span{"aria-hidden" => true} &times;
																%h4.modal-title{id: "trailer"} #{episode.title}
															.modal-body
																.embed-responsive.embed-responsive-16by9
																	.embed-responsive-item= episode.embed.html_safe
															.modal-footer
																%button.btn.btn-default{"data-dismiss" => "modal"} Close
			%hr
				= link_to 'Edit', edit_anime_path(@anime), class: "btn btn-primary"
				= link_to 'Back to Anime list', animes_path, class: "btn btn-default"